import sys
from pathlib import Path

# Ensure backend root is on sys.path for direct execution
_backend_dir = str(Path(__file__).resolve().parents[2])
if _backend_dir not in sys.path:
    sys.path.insert(0, _backend_dir)

import asyncio
import concurrent.futures
import json
import logging
import time
from typing import List, Dict, Any, Optional

from pydantic import BaseModel, Field
from pi_agent.tools.base import Tool, Sandbox

from app.rag.retriever import RAGService
from app.skills.ship30_writer import Ship30Writer

logger = logging.getLogger(__name__)


_main_event_loop: Optional[asyncio.AbstractEventLoop] = None


def set_main_event_loop(loop: Optional[asyncio.AbstractEventLoop]) -> None:
    """Sets the primary FastAPI event loop reference for thread-safe async scheduling."""
    global _main_event_loop
    _main_event_loop = loop


def _run_async(coro: Any) -> Any:
    """Executes an async coroutine safely across both running and non-running event loops."""
    global _main_event_loop

    # If the main event loop is active and running, and we are running inside a worker thread
    if _main_event_loop is not None and _main_event_loop.is_running():
        try:
            curr_loop = asyncio.get_running_loop()
        except RuntimeError:
            curr_loop = None

        if curr_loop is not _main_event_loop:
            # Safely schedule on the main event loop preserving database connections
            future = asyncio.run_coroutine_threadsafe(coro, _main_event_loop)
            return future.result()

    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = None

    if loop and loop.is_running():
        # Execute in a dedicated worker thread to avoid blocking the running event loop
        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
            return executor.submit(lambda: asyncio.run(coro)).result()
    else:
        return asyncio.run(coro)


class AgentResponse(BaseModel):
    """Structured response returned by LennyAgent."""

    selected_tool: str = Field(..., description="The name of the tool selected and executed by the agent.")
    answer: str = Field(..., description="The textual answer or content generated by the tool.")
    sources: List[str] = Field(default_factory=list, description="Source episodes or citations when available.")
    artifact: bool = Field(default=False, description="Whether this response is an artifact for Artifact Viewer.")
    markdown_content: Optional[str] = Field(default=None, description="Full markdown content of the artifact.")
    html_content: Optional[str] = Field(default=None, description="HTML rendered content of the artifact.")
    word_count: Optional[int] = Field(default=None, description="Total word count for generated articles or responses.")


# =============================================================================
# Native Pi Coding Agent Tool Builders
# =============================================================================

def build_podcast_rag_tool(rag_service: Optional[RAGService] = None) -> Tool:
    """Builds a native Pi Coding Agent Tool for podcast transcript Q&A."""
    service = rag_service or RAGService()

    def handler(args: Dict[str, Any], sandbox: Sandbox) -> str:
        question = args.get("question", "")
        # Ensure at least 5 chunks are retrieved so small models do not starve context
        top_k = max(5, int(args.get("top_k", 6)))

        t0 = time.time()
        logger.info(
            "PodcastRAGTool invoked | Rewritten Query: '%s' | top_k: %d",
            question, top_k,
            extra={"rewritten_query": question, "top_k": top_k}
        )
        try:
            rag_response = _run_async(service.answer(question=question, top_k=top_k))
            duration = round(time.time() - t0, 3)
            logger.info(
                "PodcastRAGTool execution finished",
                extra={"duration_s": duration, "sources_count": len(rag_response.sources)}
            )
            # Return JSON string so caller can extract both answer and sources
            return json.dumps({
                "answer": rag_response.answer,
                "sources": rag_response.sources
            })
        except Exception as exc:
            duration = round(time.time() - t0, 3)
            logger.error(
                "PodcastRAGTool execution failed: %s",
                exc,
                extra={"duration_s": duration, "question": question},
                exc_info=True
            )
            return json.dumps({
                "error": str(exc),
                "answer": f"Error searching transcripts: {exc}",
                "sources": []
            })

    return Tool(
        name="PodcastRAGTool",
        description=(
            "Search and retrieve grounded insights from Lenny's Podcast transcripts. "
            "Use this tool whenever the user asks questions, seeks advice, or inquires about "
            "product management, feature prioritization, customer retention, growth loops, "
            "metrics (e.g. CAC, LTV, NRR), hiring, or startup leadership."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "question": {
                    "type": "string",
                    "description": "The specific question to search podcast transcripts for."
                },
                "top_k": {
                    "type": "integer",
                    "description": "Number of transcript chunks to retrieve (default: 5).",
                    "default": 5
                }
            },
            "required": ["question"]
        },
        handler=handler,
        mutating=False
    )


def build_ship30_tool(
    writer: Optional[Ship30Writer] = None,
    retriever: Optional[Any] = None,
) -> Tool:
    """Builds a native Pi Coding Agent Tool for Ship 30 for 30 essays."""
    essay_writer = writer or Ship30Writer(retriever=retriever)
    tool_retriever = retriever

    def _get_tool_retriever() -> Optional[Any]:
        nonlocal tool_retriever
        if tool_retriever is not None:
            return tool_retriever
        from unittest.mock import Mock, AsyncMock, MagicMock
        if isinstance(essay_writer, (Mock, AsyncMock, MagicMock)):
            return None
        if hasattr(essay_writer, "_get_retriever"):
            return essay_writer._get_retriever()
        try:
            from app.rag.retriever import Retriever
            tool_retriever = Retriever()
            return tool_retriever
        except Exception as exc:
            logger.warning("Retriever unavailable in build_ship30_tool: %s", exc)
            return None

    def handler(args: Dict[str, Any], sandbox: Sandbox) -> str:
        topic = (
            args.get("topic")
            or args.get("user_query")
            or args.get("query")
            or args.get("prompt")
            or args.get("title")
            or (next((str(v) for v in args.values() if isinstance(v, str) and v.strip()), "") if args else "")
            or ""
        )
        context = args.get("context") or args.get("context_data")

        t0 = time.time()
        logger.info(
            "Ship30Tool handler invoked by Pi Agent",
            extra={"topic": topic, "has_context": bool(context)}
        )
        try:
            # 1. Retrieve relevant transcript chunks using the existing RAG retrieval pipeline
            sources: List[str] = []
            context_data = context or ""

            if not context_data:
                active_retriever = _get_tool_retriever()
                if active_retriever:
                    try:
                        chunks = _run_async(active_retriever.retrieve(query=topic, top_k=8))
                        if chunks:
                            max_sim = max(c.similarity_score for c in chunks)
                            if max_sim < 0.65:
                                logger.info("Ship30Tool: Chunks for '%s' below similarity threshold (max %.4f < 0.65)", topic, max_sim)
                                chunks = []

                        if chunks:
                            sources = list(dict.fromkeys([c.episode_title for c in chunks]))
                            context_blocks = []
                            for i, chunk in enumerate(chunks, start=1):
                                context_blocks.append(
                                    f"--- Transcript Excerpt {i} (Episode: \"{chunk.episode_title}\") ---\n"
                                    f"{chunk.content.strip()}"
                                )
                            context_data = "\n\n".join(context_blocks)
                            logger.info(
                                "Ship30Tool retrieved %d chunks across %d episodes",
                                len(chunks), len(sources)
                            )
                    except Exception as exc:
                        logger.warning("Ship30Tool retrieval failed: %s", exc)

            # 2. Pass context_data and user_query into Ship30Writer
            essay = _run_async(essay_writer.write(
                topic=topic,
                context=context_data,
                user_query=topic,
                context_data=context_data
            ))
            all_sources = list(dict.fromkeys(sources + getattr(essay, "sources", [])))
            duration = round(time.time() - t0, 3)

            is_insufficient = (
                str(essay).strip() == "Not enough transcript evidence available."
                or "not enough transcript evidence available" in str(essay).lower()
            )

            if is_insufficient:
                logger.info("Ship30Tool: Insufficient transcript evidence found for topic '%s'", topic)
                return json.dumps({
                    "answer": "Not enough transcript evidence available.",
                    "sources": [],
                    "artifact": False,
                    "markdown_content": None,
                    "html_content": None
                })

            markdown_text = getattr(essay, "markdown_content", None) or str(essay)
            html_text = getattr(essay, "html_content", None)
            if not html_text:
                try:
                    from markdown_it import MarkdownIt
                    html_text = f'<article class="ship30-article">\n{MarkdownIt().render(markdown_text)}\n</article>'
                except Exception:
                    html_text = f'<article class="ship30-article">\n<div>{markdown_text}</div>\n</article>'

            word_count = getattr(essay, "word_count", None)
            if word_count is None and markdown_text:
                word_count = len(markdown_text.strip().split())

            logger.info(
                "Ship30Tool execution finished",
                extra={"duration_s": duration, "essay_length": len(markdown_text), "word_count": word_count, "sources_count": len(all_sources)}
            )
            return json.dumps({
                "answer": markdown_text,
                "sources": all_sources,
                "artifact": True,
                "markdown_content": markdown_text,
                "html_content": html_text,
                "word_count": word_count
            })
        except Exception as exc:
            duration = round(time.time() - t0, 3)
            logger.error(
                "Ship30Tool execution failed: %s",
                exc,
                extra={"duration_s": duration, "topic": topic},
                exc_info=True
            )
            return json.dumps({
                "error": str(exc),
                "answer": f"Error generating Ship30 essay: {exc}",
                "sources": [],
                "artifact": False,
                "markdown_content": None,
                "html_content": None
            })

    return Tool(
        name="Ship30Tool",
        description=(
            "Write and generate a complete Ship 30 for 30 style long-form article "
            "(minimum 1,000 words, target 1,250 words) grounded strictly in podcast transcripts. "
            "Follows the required structure: Hook, Problem, Insight, Lesson, Application, Action Steps, Conclusion, Sources. "
            "Use this tool whenever the user requests a Ship30 article, Ship30 essay, blog post, long-form content, newsletter, "
            "or asks to write, draft, or compose an article or essay."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "topic": {
                    "type": "string",
                    "description": "The topic, theme, or title for the Ship 30 atomic essay."
                },
                "context": {
                    "type": "string",
                    "description": "Optional background context, outline, or key points to incorporate."
                }
            },
            "required": ["topic"]
        },
        handler=handler,
        mutating=False
    )


# =============================================================================
# Compatibility Wrappers for Direct Execution and Testing
# =============================================================================

class PodcastRAGTool:
    """Wrapper class providing direct .run() interface for PodcastRAGTool."""

    name: str = "PodcastRAGTool"
    description: str = "Answers questions based on podcast transcripts using RAG retrieval."

    def __init__(self, rag_service: Optional[RAGService] = None):
        self.rag_service = rag_service or RAGService()
        self.tool = build_podcast_rag_tool(self.rag_service)

    async def run(self, question: str, top_k: int = 5) -> Dict[str, Any]:
        """Direct async execution."""
        rag_response = await self.rag_service.answer(question=question, top_k=top_k)
        return {"answer": rag_response.answer, "sources": rag_response.sources}


class Ship30Tool:
    """Wrapper class providing direct .run() interface for Ship30Tool."""

    name: str = "Ship30Tool"
    description: str = "Generates an authentic Ship 30 for 30 long-form essay (~1,250 words) on a given topic."

    def __init__(self, writer: Optional[Ship30Writer] = None, retriever: Optional[Any] = None):
        self.writer = writer or Ship30Writer(retriever=retriever)
        self.retriever = retriever
        self.tool = build_ship30_tool(self.writer, retriever=self.retriever)

    async def run(self, topic: str, context: Optional[str] = None) -> str:
        """Direct async execution."""
        essay = await self.writer.write(topic=topic, context=context)
        return essay
